project:
  type: book
  output-dir: docs

book:
  title: "biol827-graduate_statistics"
  author: "Norah Jones"
  date: "8/6/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - module3_4.qmd
    - module5.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

